In [48]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.2.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [49]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
a

: 

In [51]:
a[1] = 'string'

ValueError: invalid literal for int() with base 10: 'string'

In [ ]:
a[0]

In [ ]:
a[1:]

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

b = a[3:]

b[0] = 10

a

array([ 1,  2,  3, 10,  5,  6])

In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

: 

In [ ]:
a[0][1]

2

In [ ]:
a[0, 1:]

array([2, 3])

In [ ]:
a[:, 1:]

array([[2, 3],
       [5, 6]])

In [ ]:
a.ndim

2

In [ ]:
a.shape

(2, 3)

In [ ]:
a.size

6

In [ ]:
a.dtype

dtype('int32')

In [ ]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [ ]:
np.empty((2, 3))


array([[6.23042070e-307, 1.33512376e-306, 1.11261230e-306],
       [7.56577399e-307, 9.34600963e-307, 1.05699581e-307]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [ ]:
np.linspace(0, 10, 5)  # 5 чисел от 0 до 10 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

SORT AND CONCATENATE

In [ ]:
a = np.array([2, 1, 4, 5, 3, 7, 6, 8, 9, 10])

In [ ]:
np.sort(a)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.argsort(a)

array([1, 0, 4, 2, 3, 6, 5, 7, 8, 9], dtype=int64)

In [ ]:
np.searchsorted(a, 6) # поиск 6 в отсортированном списке

5

In [ ]:
np.partition(a, (3, 1))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = np.array([[2, 1, 4, 9, 3], [7, 6, 8, 5, 10]])
a

array([[ 2,  1,  4,  9,  3],
       [ 7,  6,  8,  5, 10]])

In [ ]:
np.sort(a, axis=1)

array([[ 1,  2,  3,  4,  9],
       [ 5,  6,  7,  8, 10]])

In [ ]:
np.sort(a, axis=0)

array([[ 2,  1,  4,  5,  3],
       [ 7,  6,  8,  9, 10]])

In [ ]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([6, 7, 8, 9, 10])

In [ ]:
np.concatenate((a, b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [61]:
Изменение формы

SyntaxError: invalid syntax (29088520.py, line 1)

In [57]:
a =np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [58]:
a.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [59]:
a.reshape(2, 3, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [60]:
a.reshape(2, -1, 2) # -1 -любое число 

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [62]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [63]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [64]:
a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [65]:
np.expand_dims(a, axis=0)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [66]:
np.expand_dims(a, axis=1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

# Индексация и фильтрация

In [73]:
a = np.random.randint(0, 10, 10)
a

array([7, 0, 4, 1, 3, 2, 3, 2, 2, 6])

In [74]:
a[:5]

array([7, 0, 4, 1, 3])

In [75]:
a[a < 5]

array([0, 4, 1, 3, 2, 3, 2, 2])

In [76]:
a < 5

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [77]:
a[a%2==0]

array([0, 4, 2, 2, 2, 6])

In [80]:
a[(a%2==0) & (a < 5)]

array([0, 4, 2, 2, 2])

# Математические операции 

In [81]:
a = np.random.randint(0, 10, 10)
a

array([3, 1, 6, 7, 0, 0, 7, 0, 0, 2])

In [82]:
b = np.random.randint(0, 10, 10)
b

array([8, 2, 4, 2, 2, 1, 3, 9, 9, 0])

In [83]:
a + 5.4

array([ 8.4,  6.4, 11.4, 12.4,  5.4,  5.4, 12.4,  5.4,  5.4,  7.4])

In [84]:
a * 5.4

array([16.2,  5.4, 32.4, 37.8,  0. ,  0. , 37.8,  0. ,  0. , 10.8])

In [85]:
a + b

array([11,  3, 10,  9,  2,  1, 10,  9,  9,  2])

In [86]:
a * b

array([24,  2, 24, 14,  0,  0, 21,  0,  0,  0])

In [91]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[2, 2, 2], [2, 2, 2]])
a, b


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[2, 2, 2],
        [2, 2, 2]]))

In [93]:
a.T @ b

array([[10, 10, 10],
       [14, 14, 14],
       [18, 18, 18]])

In [92]:
a @ b.T

array([[12, 12],
       [30, 30]])

In [94]:
a.min()

1

In [95]:
a.max()

6

In [96]:
a.sum()

21

In [97]:
a.mean()

3.5

In [98]:
a.std()

1.707825127659933